# Generated by Django 3.1.5 on 2021-02-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=25)),
                ('price', models.BigIntegerField(max_length=10)),
                ('warrenty', models.BooleanField(max_length=1)),
            ],
        ),
    ]
